{% set name = "semantic_version" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bdabb6d336998cbb378d4b9db3a4b56a1e3235701dc05ea2690d9a997ed5041c

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - semantic_version

about:
  home: https://github.com/rbarrois/python-semanticversion
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library implementing the 'SemVer' scheme.
  description: |
    This small python library provides a few tools to handle SemVer in Python. 
    It follows strictly the 2.0.0 version of the SemVer scheme.
  doc_url: https://python-semanticversion.readthedocs.io
  dev_url: https://github.com/rbarrois/python-semanticversion

extra:
  recipe-maintainers:
    - druvus
